# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 463df70e9061ce62ec845494dc95f38f7972f23558ba0fbc72bec403b5254dea3cccd7cb3fad3009ad8758f887826e7031e3dd51adefa6a47650db936c37e681

test:
  secret_key_base: 7bbeb11644305cd5ed6069ac99809bcdc3c64739cf726bd2619bda90a948075086f3edbe25ecb6cb63e8f90089c39ca77160f59085b432177330f838157b53ee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
